import type { Metadata } from "next";
import { Nunito_Sans, Amatic_SC } from "next/font/google";
import "@/css/globals.css";
import "@/css/embla.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { ContactDialog } from "@/components/layout/contact-dialog";
import { builder } from "@builder.io/sdk";
import { ScrollToTopButton } from "@/components/layout/scroll-up-button";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "1000"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const settings = await builder.get("website-general-setting").toPromise();

  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <Header />
        {/* <ContactDialog /> */}
        {children}
        <ScrollToTopButton />
        <Footer />
      </body>
    </html>
  );
}
